GRANT CREATE STAGE ON SCHEMA UDYAM.RAW TO ROLE UDYAM_LOADER;

CREATE STAGE UDYAM.RAW.S3_STAGE
    STORAGE_INTEGRATION = UDYAM_S3_INT
    URL = 's3://supplier-udyam-raw/udyam/raw/'
    FILE_FORMAT = UDYAM.RAW.UDYAM_CSV_FORMAT;

GRANT USAGE ON STAGE UDYAM.RAW.S3_STAGE TO ROLE UDYAM_LOADER;

-- Verify it can see files
LIST @UDYAM.RAW.S3_STAGE;
