-- ── Warehouse ──────────────────────────────────────────────────────────────
CREATE WAREHOUSE IF NOT EXISTS UDYAM_WH
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

-- ── Database + schema ──────────────────────────────────────────────────────
CREATE DATABASE IF NOT EXISTS UDYAM;
CREATE SCHEMA IF NOT EXISTS UDYAM.RAW;

-- ── Role ───────────────────────────────────────────────────────────────────
CREATE ROLE IF NOT EXISTS UDYAM_LOADER;

GRANT USAGE ON WAREHOUSE UDYAM_WH      TO ROLE UDYAM_LOADER;
GRANT USAGE ON DATABASE  UDYAM         TO ROLE UDYAM_LOADER;
GRANT USAGE ON SCHEMA    UDYAM.RAW     TO ROLE UDYAM_LOADER;

-- ── Tables ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS UDYAM.RAW.MSME (
    LG_ST_CODE          VARCHAR,
    STATE               VARCHAR,
    LG_DT_CODE          VARCHAR,
    DISTRICT            VARCHAR,
    PINCODE             VARCHAR,
    REGISTRATION_DATE   VARCHAR,
    ENTERPRISE_NAME     VARCHAR,
    COMMUNICATION_ADDRESS VARCHAR,
    ACTIVITIES          VARCHAR,
    _RUN_ID             VARCHAR,
    _STATE              VARCHAR,
    _BATCH_ID           VARCHAR,
    _SOURCE_FILE        VARCHAR,
    _SOURCE_OFFSET      NUMBER,
    _INGESTED_AT        TIMESTAMP_LTZ
);

CREATE TABLE IF NOT EXISTS UDYAM.RAW.INGESTION_BATCH (
    RUN_ID          VARCHAR,
    BATCH_ID        VARCHAR NOT NULL PRIMARY KEY,
    STATE           VARCHAR,
    SOURCE_FILE     VARCHAR,
    SOURCE_OFFSET   NUMBER,
    EXPECTED_ROWS   NUMBER,
    LOADED_ROWS     NUMBER,
    CHECKSUM        VARCHAR,
    LOAD_STATUS     VARCHAR,
    LOADED_AT       TIMESTAMP_LTZ,
    ERROR_MESSAGE   VARCHAR
);

-- ── Table privileges ───────────────────────────────────────────────────────
GRANT INSERT, SELECT ON TABLE UDYAM.RAW.MSME             TO ROLE UDYAM_LOADER;
GRANT INSERT, SELECT, UPDATE ON TABLE UDYAM.RAW.INGESTION_BATCH TO ROLE UDYAM_LOADER;

-- ── File formats (referenced in the loader SQL) ────────────────────────────
CREATE FILE FORMAT IF NOT EXISTS UDYAM.RAW.UDYAM_CSV_FORMAT
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL')
    EMPTY_FIELD_AS_NULL = TRUE;

CREATE FILE FORMAT IF NOT EXISTS UDYAM.RAW.UDYAM_JSON_FORMAT
    TYPE = JSON
    STRIP_OUTER_ARRAY = FALSE;

GRANT USAGE ON FILE FORMAT UDYAM.RAW.UDYAM_CSV_FORMAT  TO ROLE UDYAM_LOADER;
GRANT USAGE ON FILE FORMAT UDYAM.RAW.UDYAM_JSON_FORMAT TO ROLE UDYAM_LOADER;

-- ── Service user ───────────────────────────────────────────────────────────
CREATE USER IF NOT EXISTS UDYAM_SVC
    PASSWORD            = 'ReplaceWithStrongPassword!'
    DEFAULT_ROLE        = UDYAM_LOADER
    DEFAULT_WAREHOUSE   = UDYAM_WH
    DEFAULT_NAMESPACE   = UDYAM.RAW
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE UDYAM_LOADER TO USER UDYAM_SVC;
